# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OnSSET
                                 A QGIS plugin
 This tool can be used to extract datasets to excel in order to create the necessary input file for a basic OnSSET analysis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-07-16
        copyright            : (C) 2018 by Babak Khavari
        email                : khavari@kth.se
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OnSSET class from file OnSSET.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .OnSSET import OnSSET
    return OnSSET(iface)
